class Location {
  final String category;
  final String name;
  final String location;
  final String visitingHours;
  final String closingTime;
  final String description;
  final double price;
  final List<String> reviews;
  final String preferredTime;
  final String priority;
  final int duration;
  final String image;

  Location({
    required this.category,
    required this.name,
    required this.location,
    required this.visitingHours,
    required this.closingTime,
    required this.description,
    required this.price,
    required this.reviews,
    required this.preferredTime,
    required this.priority,
    required this.duration,
    required this.image,
  });
}

List<Location> locations = [
  Location(
    category: 'Places to eat',
    name: 'Maxwell Food Centre',
    location: '1 Kadayanallur Street, Singapore',
    visitingHours: '10:00 - 21:00',
    closingTime: '21:00',
    description: 'Hawker center offering a variety of local dishes, including Hainanese chicken rice and laksa.',
    price: 30,
    reviews: ['Amazing view!', 'Must-visit restaurant.'],
    preferredTime: 'Afternoon',
    priority: '2',
    duration: 1,
    image: 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Singapore_Skyline_2019-10.jpg',
  ),
  Location(
    category: 'Places to eat',
    name: 'Chinatown Complex Food Centre',
    location: '335 Smith Street, Singapore',
    visitingHours: '10:00 - 21:00',
    closingTime: '21:00',
    description: 'Large hawker center in Chinatown with a wide array of affordable and delicious local food options.',
    price: 10,
    reviews: ['Amazing food!', 'Must-visit restaurant.'],
    preferredTime: 'Evening',
    priority: '3',
    duration: 1,
    image: 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Singapore_Skyline_2019-10.jpg',
  ),
  Location(
    category: 'Places to eat',
    name: 'Newton Food Centre',
    location: '500 Clemenceau Avenue North, Singapore',
    visitingHours: '10:00 - 21:00',
    closingTime: '21:00',
    description: 'Popular open-air hawker center known for its seafood and local delights.',
    price: 10,
    reviews: ['Amazing Food!', 'Must-visit restaurant.'],
    preferredTime: 'Evening',
    priority: '3',
    duration: 1,
    image: 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Singapore_Skyline_2019-10.jpg',
  ),
  // Monuments
  Location(
    category: 'Monument',
    name: 'Merlion Park',
    location: 'Fullerton Road, Singapore',
    visitingHours: '00:00 - 23:00',
    closingTime: '23:00',
    description: 'Iconic statue of a mythical creature with a lion\'s head and a fish\'s tail, overlooking Marina Bay.',
    price: 0,
    reviews: ['Amazing view!', 'Must-visit landmark.'],
    preferredTime: 'Night',
    priority: '3',
    duration: 1,
    image: 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Singapore_Skyline_2019-10.jpg',
  ),
  Location(
    category: 'Monument',
    name: 'Sri Mariamman Temple',
    location: '244 South Bridge Road, Singapore',
    visitingHours: '07:00 - 12:00',
    closingTime: '12:00',
    description: 'Oldest Hindu temple in Singapore, known for its stunning Dravidian architecture and intricate sculptures.',
    price: 0,
    reviews: ['Beautiful architecture!', 'Spiritual experience.'],
    preferredTime: 'Morning',
    priority: '1',
    duration: 1,
    image: 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Singapore_Skyline_2019-10.jpg',
  ),
  Location(
    category: 'Monument',
    name: 'National Museum of Singapore',
    location: '93 Stamford Road, Singapore',
    visitingHours: '10:00 - 19:00',
    closingTime: '19:00',
    description: 'Museum showcasing the history and culture of Singapore through interactive exhibits and artifacts.',
    price: 15,
    reviews: ['Educational and engaging!', 'Rich collection.'],
    preferredTime: 'Afternoon',
    priority: '2',
    duration: 1,
    image: 'https://www.visitsingapore.com/content/dam/desktop/global/see-do-singapore/history/national-museum-of-singapore-carousel01-rect.jpeg',
  ),
  Location(
    category: 'Monument',
    name: 'Singapore Art Museum',
    location: '71 Bras Basah Road, Singapore',
    visitingHours: '10:00 - 19:00',
    closingTime: '19:00',
    description: 'Contemporary art museum housed in a restored 19th-century school building.',
    price: 12,
    reviews: ['Art lover\'s paradise!', 'Diverse exhibitions.'],
    preferredTime: 'Afternoon',
    priority: '2',
    duration: 1,
    image: 'https://www.thebestsingapore.com/wp-content/uploads/2015/07/Singapore-Art-Museum.jpg',
  ),
  Location(
    category: 'Monument',
    name: 'Esplanade - Theatres on the Bay',
    location: '1 Esplanade Drive, Singapore',
    duration: 2,
    visitingHours: '10:00 - 19:00',
    closingTime: '19:00',
    description: 'Iconic performing arts center with theaters, concert halls, and waterfront views.',
    price: 0,
    reviews: ['Cultural hub!', 'Impressive architecture.'],
    preferredTime: 'Night',
    priority: '3',
    image: 'https://www.esplanade.com/-/media/Esplanade/Images/Visit-Esplanade/Tours-and-Experiences/garden-tour-01.ashx?rev=be0385e20e7a40d585fc92c466b7209c&hash=EB8FB0E59B4E8D12B697FBB6C605A635',
  ),
  Location(
    category: 'Monument',
    name: 'Fort Siloso',
    location: 'Siloso Road, Sentosa, Singapore',
    visitingHours: '10:00 - 18:00',
    closingTime: '18:00',
    description: 'Historical coastal fort with exhibits, tunnels, and panoramic views of the sea.',
    price: 12,
    reviews: ['Rich history!', 'Great for history buffs.'],
    preferredTime: 'Morning',
    priority: '1',
    duration: 1,
    image: 'https://onecms-res.cloudinary.com/image/upload/s--av_yTgnt--/f_auto,q_auto/c_fill,g_auto,h_676,w_1200/v1/mediacorp/cna/image/2022/02/15/6-inch_breech_loading_bl_gun_emplacement_with_underground_magazine_image_courtesy_of_national_heritage_board.jpg?itok=kXcnDSoW',
  ),
  Location(
    category: 'Monument',
    name: 'Civilian War Memorial',
    location: 'Beach Road, Singapore',
    visitingHours: '00:00 - 24:00',
    closingTime: '23:59',
    description: 'Memorial honoring civilians who perished during the Japanese occupation of Singapore.',
    price: 0,
    reviews: ['Solemn tribute!', 'Quiet reflection.'],
    preferredTime: 'Full Day',
    priority: '4',
    duration: 3,
    image: 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Singapore_Skyline_2019-10.jpg',
  ),
];
